apiVersion: v1
kind: Service
metadata:
  name: {{ include "uichart.name" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uichart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uichart.selectorLabels" . | nindent 4 }}
